services:
  web:
    ports: !override
      - '127.0.0.1:3100:3000'
  streaming:
    ports: !override
      - '127.0.0.1:4100:4000'
  caddy:
    image: caddy:2
    restart: always
    ports:
      - '127.0.0.1:443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
    networks:
      - external_network
    depends_on:
      - web
      - streaming
